# -*- coding: utf-8 -*-
"""Mini_Research_Search_Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1317Kn4eGaEXI8NKsNye5QkzRIf2UyRFs
"""

import os

os.makedirs("abstracts", exist_ok=True)

abstracts = {
    "001.txt": "Title: Cancer Biology\nCancer research explores the molecular basis of cancer.",
    "002.txt": "Title: Climate Change\nThe effects of climate change on biodiversity are vast.",
    "003.txt": "Title: Protein Folding\nProtein misfolding is linked to many neurodegenerative diseases.",
}

for filename, content in abstracts.items():
    with open(os.path.join("abstracts", filename), "w") as f:
        f.write(content)

print("Sample abstracts created!")

import os

def load_files(folder):
    files_data = {}
    for filename in os.listdir(folder):
        if filename.endswith(".txt"):
            with open(os.path.join(folder, filename), 'r', encoding='utf-8') as file:
                content = file.read()
                files_data[filename] = content
    return files_data

def search_files(files_data, query):
    query = query.lower()
    results = []
    for filename, content in files_data.items():
        if query in content.lower():
            first_line = content.strip().split("\n")[0]
            results.append((filename, first_line))
    return results

folder = "abstracts"
files_data = load_files(folder)

# Example search
query = "cancer"
results = search_files(files_data, query)

if results:
    print(f"Results for '{query}':")
    for filename, title in results:
        print(f"- {filename} | Title: {title}")
else:
    print(f"No results found for '{query}'.")

while True:
    query = input("\nSearch query (empty to quit): ").strip()
    if query == "":
        break
    results = search_files(files_data, query)
    if results:
        for filename, title in results:
            print(f"- {filename} | Title: {title}")
    else:
        print(f"No results found for '{query}'.")